name: Bookstore WebApp CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci || npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli@19.2.9

      - name: Build Application
        run: npm run build -- --configuration=production

      - name: Run Unit Tests
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: coverage/
          if-no-files-found: warn

  playwright-tests:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Root Dependencies
        run: |
          npm ci || npm install
          npm install -g @angular/cli@19.2.9

      - name: Install Playwright Dependencies
        working-directory: playwright-tests
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run Mock Tests
        working-directory: playwright-tests
        env:
          PLAYWRIGHT_REUSE_SERVER: "true"
        run: |
          npm run mock -- --shard=${{ matrix.shard }}/2 --reporter=json,html

      - name: Run Feature Tests
        working-directory: playwright-tests
        env:
          PLAYWRIGHT_REUSE_SERVER: "true"
          NODE_ENV: "test"
          BROWSER: "chromium"
          CUCUMBER_PARALLEL: "2"
          CUCUMBER_SHARD: "${{ matrix.shard }}"
        run: |
          npm run feature:chrome -- --parallel 2 --shard ${{ matrix.shard }}/2

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.shard }}
          path: |
            playwright-tests/test-results/
            playwright-tests/playwright-report/
          if-no-files-found: warn

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-${{ matrix.shard }}
          path: playwright-tests/reports/cucumber/
          if-no-files-found: warn

      - name: Upload Angular Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: angular-logs-${{ matrix.shard }}
          path: angular.log

      - name: Stop Angular App
        if: always()
        run: |
          npx kill-port 4200 || true
          sleep 2

  merge-reports:
    needs: playwright-tests
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        working-directory: playwright-tests
        run: npm ci

      - name: Create Report Directories
        run: |
          mkdir -p playwright-tests/merged-reports/playwright
          mkdir -p playwright-tests/merged-reports/cucumber
          mkdir -p playwright-tests/temp-reports

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          path: playwright-tests/temp-reports
          merge-multiple: true

      - name: Download Cucumber Reports
        uses: actions/download-artifact@v4
        with:
          pattern: cucumber-report-*
          path: playwright-tests/temp-reports/cucumber
          merge-multiple: true

      - name: Debug Directory Structure
        run: |
          echo "Temp reports structure:"
          ls -R playwright-tests/temp-reports/

      - name: Merge Playwright Reports
        working-directory: playwright-tests
        run: |
          # Check for test results
          if [ -d "temp-reports/test-results" ]; then
            echo "Found test results directory"
            ls -la temp-reports/test-results/
            
            # Create a directory for JSON reports
            mkdir -p temp-json-reports
            
            # Find and copy all JSON reports
            find temp-reports/test-results -name "*.json" -exec cp {} temp-json-reports/ \;
            
            echo "Contents of temp-json-reports:"
            ls -la temp-json-reports/
            
            # Merge reports if we have JSON files
            if [ "$(ls -A temp-json-reports)" ]; then
              echo "Merging JSON reports..."
              npx playwright merge-reports --reporter html temp-json-reports
              cp -r playwright-report/* merged-reports/playwright/
            else
              echo "No JSON reports found to merge"
              # Fallback to copying HTML report if available
              if [ -d "temp-reports/playwright-report" ]; then
                echo "Copying existing HTML report"
                cp -r temp-reports/playwright-report/* merged-reports/playwright/
              fi
            fi
          else
            echo "No test results directory found"
            # Fallback to copying HTML report if available
            if [ -d "temp-reports/playwright-report" ]; then
              echo "Copying existing HTML report"
              cp -r temp-reports/playwright-report/* merged-reports/playwright/
            fi
          fi

      - name: Merge Cucumber Reports
        working-directory: playwright-tests
        run: |
          if [ -d "temp-reports/cucumber" ]; then
            cp -r temp-reports/cucumber/*/* merged-reports/cucumber/
          fi

      - name: Upload Merged Reports
        uses: actions/upload-artifact@v4
        with:
          name: merged-test-reports
          path: playwright-tests/merged-reports/
          if-no-files-found: warn

  deploy-report:
    needs: merge-reports
    runs-on: ubuntu-latest
    if: always()
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Merged Reports
        uses: actions/download-artifact@v4
        with:
          name: merged-test-reports
          path: test-results

      - name: Create index.html
        run: |
          cat > test-results/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Test Reports</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h1 { color: #333; }
              .report-section { margin: 20px 0; }
              .report-link {
                display: inline-block;
                padding: 10px 20px;
                background: #007bff;
                color: white;
                text-decoration: none;
                border-radius: 5px;
                margin: 10px 0;
              }
              .report-link:hover {
                background: #0056b3;
              }
            </style>
          </head>
          <body>
            <h1>Test Reports</h1>
            <div class="report-section">
              <h2>Playwright Tests Report</h2>
              <a class="report-link" href="./playwright/index.html">View Playwright Report</a>
            </div>
            <div class="report-section">
              <h2>Cucumber Tests Report</h2>
              <a class="report-link" href="./cucumber/index.html">View Cucumber Report</a>
            </div>
          </body>
          </html>
          EOL

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: test-results

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4