name: Bookstore WebApp CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci || npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli@19.2.9

      - name: Build Application
        run: npm run build -- --configuration=production

      - name: Run Unit Tests
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: coverage/
          if-no-files-found: warn

  playwright-tests:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Root Dependencies
        run: |
          npm ci || npm install
          npm install -g @angular/cli@19.2.9

      - name: Install Playwright Dependencies
        working-directory: playwright-tests
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run Mock Tests
        working-directory: playwright-tests
        env:
          PLAYWRIGHT_REUSE_SERVER: "true"
        run: |
          npm run mock -- --shard=${{ matrix.shard }}/2

      - name: Run Feature Tests
        working-directory: playwright-tests
        env:
          PLAYWRIGHT_REUSE_SERVER: "true"
          NODE_ENV: "test"
          BROWSER: "chromium"
          CUCUMBER_PARALLEL: "2"
          CUCUMBER_SHARD: "${{ matrix.shard }}"
        run: |
          npm run feature:chrome -- --parallel 2 --shard ${{ matrix.shard }}/2

      - name: Generate Reports
        if: always()
        working-directory: playwright-tests
        run: |
          npm run generate:reports

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.shard }}
          path: |
            playwright-tests/playwright-report/
            playwright-tests/reports/cucumber/
            playwright-tests/test-results/
          if-no-files-found: warn

      - name: Upload Angular Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: angular-logs-${{ matrix.shard }}
          path: angular.log

      - name: Stop Angular App
        if: always()
        run: |
          npx kill-port 4200 || true
          sleep 2

  merge-reports:
    needs: playwright-tests
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Create Report Directories
        run: |
          mkdir -p merged-reports/playwright
          mkdir -p merged-reports/cucumber

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          path: all-reports
          merge-multiple: true

      - name: Merge Reports
        run: |
          cp -r all-reports/playwright-report/* merged-reports/playwright/ || true
          cp -r all-reports/reports/* merged-reports/cucumber/ || true

      - name: Upload Merged Reports
        uses: actions/upload-artifact@v4
        with:
          name: merged-test-reports
          path: merged-reports
          if-no-files-found: warn

  deploy-report:
    needs: merge-reports
    runs-on: ubuntu-latest
    if: always()
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Merged Reports
        uses: actions/download-artifact@v4
        with:
          name: merged-test-reports
          path: test-results

      - name: Create index.html
        run: |
          cat > test-results/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Test Reports</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h1 { color: #333; }
              .report-section { margin: 20px 0; }
              .report-link {
                display: inline-block;
                padding: 10px 20px;
                background: #007bff;
                color: white;
                text-decoration: none;
                border-radius: 5px;
                margin: 10px 0;
              }
              .report-link:hover {
                background: #0056b3;
              }
            </style>
          </head>
          <body>
            <h1>Test Reports</h1>
            <div class="report-section">
              <h2>Playwright Mock Tests Report</h2>
              <a class="report-link" href="./playwright/">View Report</a>
            </div>
            <div class="report-section">
              <h2>Cucumber Feature Tests Report</h2>
              <a class="report-link" href="./cucumber/">View Report</a>
            </div>
          </body>
          </html>
          EOL

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: test-results

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4